language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers python-scipy
install:
  - pip install numpy Sphinx coveralls coverage nose pygments setuptools ctree hindemith
script:
  - nosetests -a '!omp' --verbose --with-coverage --cover-package=stencil_code --cover-erase
after_success:
  - coveralls
  - curl -X POST http://readthedocs.org/build/stencil-code
notifications:
  slack: ucb-sejits:cPZxBunxagWZ763mcsIXOV0W
deploy:
  provider: pypi
  user: leonardt
  password:
    secure: ajymBFsIIjbwVAIffxebyZMfTtzdIUeBdsbWpvSSaW9evnJDRt0wKVkPcPya9NT+RwJvqQzWz+mO80mhk4Jc0WzvGsNSbUIsiDOHCx5jsmVh9xLzdtc9Kf/LVEaSAILU+VmBs9YqENhxyxI7y11JMzHim+mXsagKblzVTbKZs1A=
  on:
    tags: true
    all_branches: true
    repo: ucb-sejits/stencil_code
